### ISSUE TITLE
Completion of patches?

### ISSUE THREAD

**Issue by ghost** [jongshh/Jongsh-s-TURD-Misc-Patch#1]
I was wondering if there is any chance of existing patches covering all parts in their respective mods. I feel like the parts included in each patch are chosen deliberately, but I don't know if that is the case.

**Comment by jongshh** [comment]
For now, I'm focusing on my craft's parts first.
Once I overcome my laziness, I’ll add more parts for that.

There’s also another big project:
https://forum.kerbalspaceprogram.com/topic/225789-112x-the-felota-project-a-collection-of-textures-unlimited-recolor-depots-turds/

So, if you're interested, check it out! :)
